### ISSUE TITLE
gravatar.com found on / is not an approved link.

### ISSUE THREAD

**Issue by webguyio** [WordPress/theme-review-action#28]
https://github.com/WordPress/theme-review-action/blob/trunk/docs/ui-errors.md#page-should-not-have-unexpected-links

Is there a list of approved/whitelisted links? If so, gravatar.com should definitely be added to it.

Thanks

**Comment by StevenDufresne** [comment]
Thanks for opening an issue!  The gravatar issue came up ~1 months ago and we whitelisted the following:

```
'0.gravatar.com',
'1.gravatar.com',
'2.gravatar.com',
'secure.gravatar.com',
```
in [this commit](https://github.com/WordPress/theme-review-action/commit/691f5b20fcb070778425c3fe406ef1ce302ab07e).

Have you seen this problem recently?

**Comment by webguyio** [comment]
Looks like it was fixed the very same day that the issue came up:

https://themes.trac.wordpress.org/ticket/97160#comment:2

So, this can be closed.

Thanks
