### ISSUE TITLE
Screenshot: Enforce ratio

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/theme-review-action#41]

**Comment by carolinan** [comment]
The screenshot should be no bigger than 1200 x 900px
The ratio of width to height should be 4:3

https://github.com/WordPress/theme-check/blob/master/checks/class-screenshot-check.php

**Comment by carolinan** [comment]
I believe that this should be closed in favor of https://meta.trac.wordpress.org/ticket/5834

**Comment by StevenDufresne** [comment]
I agree, closing.
