### ISSUE TITLE
Unclear Message 

### ISSUE THREAD

**Issue by kafleg** [WordPress/theme-review-action#57]
Test Name: Should have element focus state
Found on:
Details:
Help:
https://github.com/WordPress/theme-review-action/blob/trunk/docs/ui-warnings.md#should-have-element-focus-state

Ticket: https://themes.trac.wordpress.org/ticket/103799#comment:1

**Comment by StevenDufresne** [comment]
This comment was triggered as an error. I have deleted the comment. Please feel free to delete any others.
