### ISSUE TITLE
Fatal errors are not properly detected when in html attributes.

### ISSUE THREAD

**Issue by dd32** [WordPress/theme-review-action#63]
For example, take this theme run: https://themes.trac.wordpress.org/ticket/106344#comment:6

The fatal error occured within a HTML attribute (See `echo esc_attr_()` within https://themes.trac.wordpress.org/changeset/155597) and so wasn't matched by the fatal extraction from the DOM.

I guess this means that more might need to be done to either close the attribute before outputting errors or doing some kind of string parsing on the DOM rather than simply relying upon the DOM

**Comment by StevenDufresne** [comment]
Agreed. The regular expression isn't very flexible at the moment:

https://github.com/WordPress/theme-review-action/blob/64554690d3e355c34530111cdeaa1d766b8cae11/actions/ui-check/tests/utils/helpers.js#L7
