### ISSUE TITLE
Reports should not include `test-theme`

### ISSUE THREAD

**Issue by dd32** [WordPress/theme-review-action#64]
Currently reports generated by the action include the path as `themes/test-theme/` which leaves some people confused.

There's two options I see:
 - Always install the theme into the theme-directory name
 - Rewrite the output from the action to replace `wp-content/themes/test-theme/` to be `wp-content/themes/$THEME_SLUG/`

Example: https://themes.trac.wordpress.org/ticket/105885#comment:1

**Comment by StevenDufresne** [comment]
I think the quickest way would be to rewrite the output from the action. Keeping the folder generic in this project makes the code base simpler.

**Comment by dd32** [comment]
@StevenDufresne In that case, we can close this as https://github.com/WordPress/wordpress.org/commit/fecfd88195d52c33ce9c5101d2de35bd9abc805c handles that rewrite.
