### ISSUE TITLE
Page should not have unexpected links

### ISSUE THREAD

**Issue by ghost** [WordPress/theme-review-action#73]
"en.gravatar.com" found when viewing "/?p=1" (via: single.php) is not an approved link.
See: https://github.com/WordPress/theme-review-action/blob/trunk/docs/ui-errors.md#page-should-not-have-unexpected-links

I cannot fix it. can you help me?

Thanks

**Comment by dd32** [comment]
With #74 merged this should resolve it.

@TemplateHouse @walterebert  Sorry for the delay!
